declare var _default: Readonly<{
    CSRF_TOKEN: string;
    API_LOGIN: string;
    API_EXCHANGE_CODE: string;
    API_REPUTATION: string;
    OAUTH_TOKEN: string;
    OAUTH_EXCHANGE: string;
    OAUTH_KILL_SESSION: string;
    EULA: string;
    ENTITLEMENTS: string;
    ORDER_PURCHASE: string;
    CAPTCHA_PURCHASE: string;
    DEVICE_AUTH: string;
    MANIFEST: string;
    LAUNCHER: string;
    STAGING_API: string;
    PUBLIC_BASE_URL: string;
    CLOUD_STORAGE: string;
    LIGHT_SWITCH: string;
}>;
export default _default;
